- slide/additional-panel.scss
> Fix :: additional panel buttons

- main.scss
- slide/mobile-additional-infos.scss
https://github.com/ToucanToco/tucana/pull/5716
> Colors for mobile additional infos

- slide/additional-panel.scss
https://github.com/ToucanToco/tucana/pull/5745/files
> Additional Panel :: rename share as share-tab

- slide/additional-panel.scss
- small-app/component/comments/comments.scss
Update color after design review
> Additional panel :: polishing - update colors

- new-charts/tc-tablechart.scss
cf: https://github.com/ToucanToco/tucana/pull/5721
> Hotfix :: Table Chart :: Values should have a pretty size

- colors.scss
- new-charts/components/components.scss
- new-charts/components/details.scss
- new-charts/components/serie.scss
- new-charts/tc-bullet-chart.scss
Colors for this PR : ToucanToco/tucana#5970
> Charts :: Add new details & serie components

- new-charts/components/components.scss
- new-charts/components/value.scss
- small-app/home/tiles/tile-score-card.scss
Necessary for the new score card :)
> Color tc-value according to its sentiment

- new-charts/components/bar.scss
- new-charts/components/components.scss
- new-charts/components/horizontal-bar.scss
This rename two classes to follow a component renaming.
It will only have an impact on the leader-board centered average, which is still under development.
> Feature :: horizontal-bar component

- colors.scss
Adds the `toucan` color for ToucanToco/tucana#6109
> Palette :: Add the toucan color to the palette

- new-charts/components/serie.scss
- new-charts/tc-bullet-chart.scss
- new-charts/tc-legend/tc-legend-ordinal.scss
Add the class of the new component details to the mixin colorChartsElementsByName
https://github.com/ToucanToco/tucana/pull/6120
> mixin colorChartsElementsByName :: add new details (legend) class

- new-charts/components/components.scss
- new-charts/components/details.scss
- new-charts/components/metas.scss
- new-charts/components/serie.scss
Colors for this tucana Pr: ToucanToco/tucana#6280
> Charts :: Add a new Metas component

- new-charts/components/slider-filter.scss
Split unstackable delcarations
> Fix:: Unstackable declarations for input type slider

- slide/mobile-additional-infos.scss
Need to remove/add classes to get emphasis color on recommendation icon
> Story :: Change commentary mobile classes

- new-charts/tc-linechart.scss
Need to color label with same color than line in showValues feature on the new Linechart.
Feature: https://github.com/ToucanToco/tucana/pull/6595
> Linechart :: Implement showValues 

- variables.scss
It is handled in Tucana now to have full control over responsive design.
> [compact-mode] :: remove responsive buttons font-size from camouflage

- utils/components/tc-dropdown.scss
Adapt media query to compact-mode
> [compact-mode] :: DropdownFilter

- new-charts/graphical-elements/graphical-elements.scss
- new-charts/graphical-elements/horizontal-bar-with-bullet.scss
- new-charts/tc-bullet-chart.scss
- new-charts/tc-details.scss
- new-charts/tc-legend/tc-legend-ordinal.scss
- variables.scss
* Remove old tile file to display all bullet styles in one file
* Add bullet variables to avoid duplicated color code
* Remove/Replace old comparison variable
* Add ordinal tcDetails to legend mixin to color legend based on data-type.
:link: Tucana :https://github.com/ToucanToco/tucana/pull/6689
:clock1: Laputa Bump : :construction:
> Bullet :: Add similar color for chart and tile

- charts/leaderboard.scss
- new-charts/color-elements.scss
chart dont exist anymore
tucana PR to merge first: https://github.com/ToucanToco/tucana/pull/7146
Will do a camouflage bump after
> refactor(chart): remove legacy leaderboard-centered-average

- new-charts/tc-bullet-chart.scss
- new-charts/tc-details.scss
- new-charts/tc-linechart.scss
- Replace simple quotes with double quotes
- Remove !important
> fix(data-attributes): simple quotes

- new-charts/tc-mapchart.scss
Tucana PR => https://github.com/ToucanToco/tucana/pull/8126
> feat(mapchart): manage sentiments for markers

- main.scss
- studio/slide-editor/sentiment-editor/sentiment-editor.scss
- studio/slide-editor/sentiment-editor/sentiment-selector.scss
Sentiment colors are now defined in tucana no need to use this files anymore.
> fix(sentiment): remove unecessary styles

- new-charts/tc-linechart.scss
Linked PR: https://github.com/ToucanToco/tucana/pull/10653
> fix(linechart): rename .sentiment-zone__rect > .sentiment-zone__area
